version: "3.3"

networks:
  drzavewebapi-dev:
    driver: bridge

services:
  drzavewebapi:
    image: drzavewebapi
    depends_on:
      - "robertpostgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "32808:80"
    environment:
      DB_CONNECTION_STRING: "host=RobertPostgres;port:5432;database=postgres;username=postgres;password:ss"
    networks:
      - drzavewebapi-dev
      
  robertpostgres:
    image: postgres
    ports:
      - "5432"
    restart: always
    volumes:
      - "db_volume:/var/lib/postgresql/data"
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ss"
      POSTGRES_DB: "postgres"
    networks:
      - drzavewebapi-dev
volumes:
  db_volume: