// <auto-generated />
using System;
using BusinessLogic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DAL.Migrations
{
    [DbContext(typeof(DrzavedbContext))]
    [Migration("20200120173104_Cascade Delete Added")]
    partial class CascadeDeleteAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BusinessLogic.Models.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnName("ime")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_drzave");

                    b.ToTable("drzave");
                });

            modelBuilder.Entity("BusinessLogic.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnName("ime")
                        .HasColumnType("text");

                    b.Property<int?>("Populacija")
                        .HasColumnName("populacija")
                        .HasColumnType("integer");

                    b.Property<int?>("drzava_id")
                        .HasColumnName("drzava_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_gradovi");

                    b.HasIndex("drzava_id")
                        .HasName("ix_gradovi_drzava_id");

                    b.ToTable("gradovi");
                });

            modelBuilder.Entity("BusinessLogic.Models.Grad", b =>
                {
                    b.HasOne("BusinessLogic.Models.Drzava", "Drzava")
                        .WithMany("Gradovi")
                        .HasForeignKey("drzava_id")
                        .HasConstraintName("fk_gradovi_drzave_drzava_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
